version: '3.7'
services:
  webserver:
    image: nginx:stable-alpine
    container_name: 'studatlas-webserver'
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - core
  core:
    image: pereslavtsev/studatlas-core:latest
    container_name: 'studatlas-core'
    environment:
      - NODE_ENV
      - PORT=3000
      - SERVICE_URL_AUTH=auth:5000
      - SERVICE_URL_GRABBER=grabber:5000
    depends_on:
      - auth
      - grabber
  auth:
    image: pereslavtsev/studatlas-ms-auth:latest
    container_name: 'studatlas-ms-auth'
    restart: always
    environment:
      - NODE_ENV
      - AUTH0_DOMAIN
      - AUTH0_CLIENT_ID
      - AUTH0_CLIENT_SECRET
  grabber:
    image: pereslavtsev/studatlas-ms-grabber:latest
    container_name: 'studatlas-ms-grabber'
    restart: always
    environment:
      - NODE_ENV
      - MONGODB_URI

