version: '3.7'
services:
  webserver:
    image: nginx:stable-alpine
    container_name: 'studatlas-webserver'
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - core
  core:
    image: pereslavtsev/studatlas-core:latest
    container_name: 'studatlas-core'
    environment:
      - NODE_ENV
      - PORT=3000
      - SERVICE_URL_GRABBER=grabber:50052
    depends_on:
      - grabber
  grabber:
    image: pereslavtsev/studatlas-ms-grabber:latest
    container_name: 'studatlas-ms-grabber'
    environment:
      - NODE_ENV
      - PORT=50052
      - MONGODB_URI

