version: 2.1

orbs:
  docker: circleci/docker@0.5.17

jobs:
  build:
    executor:
      name: docker/docker
      tag: '3.6'
    steps:
      - checkout
      - docker/install-docker-compose
      - docker-compose build

# workflows
workflows:
  build-and-test:
    jobs:
      - build
